# Generated by Django 4.2.9 on 2026-10-02 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_prevent_overlapping_appointments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='end_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
