# Generated by Django 4.2.9 on 2026-03-02 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import physio_clinic.apps.treatments.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visit_date', models.DateField()),
                ('chief_complaint', models.TextField()),
                ('diagnosis', models.TextField()),
                ('treatment_given', models.TextField()),
                ('treatment_plan', models.TextField(blank=True)),
                ('goals', models.TextField(blank=True)),
                ('precautions', models.TextField(blank=True)),
                ('pain_level_before', models.PositiveSmallIntegerField(blank=True, help_text='0-10 scale', null=True)),
                ('pain_level_after', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('functional_score', models.CharField(blank=True, max_length=50)),
                ('next_appointment_recommended', models.BooleanField(default=False)),
                ('follow_up_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_record', to='appointments.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_records', to='accounts.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_records', to='accounts.patientprofile')),
            ],
            options={
                'db_table': 'treatments_record',
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=physio_clinic.apps.treatments.models.treatment_file_path, validators=[physio_clinic.apps.treatments.models.validate_file_size])),
                ('file_type', models.CharField(choices=[('xray', 'X-Ray'), ('scan', 'Scan/MRI'), ('report', 'Lab Report'), ('prescription', 'Prescription'), ('other', 'Other')], default='other', max_length=20)),
                ('original_filename', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_size_bytes', models.PositiveIntegerField(default=0)),
                ('treatment_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='treatments.treatmentrecord')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'treatments_file',
            },
        ),
        migrations.AddIndex(
            model_name='treatmentrecord',
            index=models.Index(fields=['patient', 'visit_date'], name='treatments__patient_17fdb0_idx'),
        ),
    ]
